name: build-libs-go

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.7'
      - name: run unit tests
        run: cd lib-go/ && make test
      - name: upload coverage report
        uses: actions/upload-artifact@master
        with:
          name: oras-coverage-report-${{ github.sha }}
          path: libs-go/.cover/
        if: always()
